### ISSUE TITLE
array_merge issue in Client authRequest

### ISSUE THREAD

**Issue by acarpio89** [Nexmo/nexmo-php#128]
We are having the following error affecting a small portion of our users:

```
array_merge(): Argument #1 is not an array {"exception":"[object] (ErrorException(code: 0): array_merge(): Argument #1 is not an array at /var/www/app/vendor/nexmo/client/src/Client.php:205)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_merge(): ...', '/var/www/app/ve...', 205, Array)
#1 /var/www/app/vendor/nexmo/client/src/Client.php(205): array_merge(NULL, Array)
#2 /var/www/app/vendor/nexmo/client/src/Client.php(359): Nexmo\\Client::authRequest(Object(Zend\\Diactoros\\Request), Object(Nexmo\\Client\\Credentials\\Basic))
#3 /var/www/app/vendor/nexmo/client/src/Message/Client.php(48): Nexmo\\Client->send(Object(Zend\\Diactoros\\Request))
```

Seems like something is going wrong with the authentication request, but only in some specific cases. The majority of times it works nicely, so I would discard an issue with our credentials. Are there any know causes to this problem? Could it be a regional issue? (the reports we've heard are from users in UAE and China).

**Comment by lornajane** [comment]
It's not a lot of information but we appreciate the bug report regardless! I couldn't reproduce which isn't a surprise as you say it works the majority of the time. We'll keep trying and if you can keep us posted with anything more at your end, that would be helpful too.

**Comment by lornajane** [comment]
Closing due to inactivity, but please re-open if you have more information relating to this issue.
