### ISSUE TITLE
Stream not rewinding after receiving Nexmo Message object in Laravel Nexmo Channel

### ISSUE THREAD

**Issue by awebartisan** [Nexmo/nexmo-php#219]
I am sending SMS using Nexmo and **laravel/nexmo-notification-channel.** I want to use the **response**  that gets back from Nexmo. 
Fortunately, Laravel provides an event `NotificationSent` and a public property on it called `response` which contains the object of Nexmo\Message\Message and I can see all the necessary data by dumping it.
Now, I want to get the **status** of message. So I go ahead and call the available method.

`$nexmoMessage->getStatus()`

But every messaage is throwing following exception:
```ErrorException: fseek() expects parameter 1 to be resource, int given in /Users/zubairmohsin/sites/sitename/vendor/guzzlehttp/psr7/src/Stream.php:204```

### Stacktrace
```

#1 /Users/zubairmohsin/sites/sitename/vendor/guzzlehttp/psr7/src/Stream.php(204): fseek(0, 0, 0)
--
#2 /Users/zubairmohsin/sites/sitename/vendor/guzzlehttp/psr7/src/Stream.php(190): GuzzleHttp\Psr7\Stream->seek(0)
#3 /Users/zubairmohsin/sites/cartrecovery/vendor/nexmo/client-core/src/Entity/JsonResponseTrait.php(29): GuzzleHttp\Psr7\Stream->rewind()
#4 /Users/zubairmohsin/sites/sitename/app/Domain/SMS/Listeners/MessageSent.php(36): Nexmo\Message\Message->getResponseData()
#5 [internal function]: App\Domain\SMS\Listeners\MessageSent->handle(Object(Illuminate\Notifications\Events\NotificationSent))
```

**Comment by dragonmantank** [comment]
Just tested with this sample code with Laravel 7 and PHP 7.4.4:

```php
Route::get('/nexmo', function () {
    Notification::route('nexmo', '55555555555')
        ->notify(new TestNexmoNotification())
    ;
});
```

```php
class TestNexmoNotification extends Notification
{
    use Queueable;

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['nexmo'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toNexmo($notifiable)
    {
        return (new NexmoMessage)
                    ->from('66666666666')
                    ->content('This is a test message')
        ;
    }

    public function handle(NotificationSent $notification)
    {
        dd($notification->response->getStatus());
    }
}
```

And I seem to be getting a `0` back for the status, which indicates a successful send. 

Can you confirm which version of `nexmo/laravel`, `nexmo/client`, Laravel, and PHP that you are using? I would pull the package versions from `composer.lock` to see which exact ones are being pulled.

**Comment by awebartisan** [comment]
- Laravel 7.4
- PHP 7.4.2
- nexmo/laravel: ^2.0
- nexmo/client: ^2.0

I forgot to mention explicitly that my Notification and Listener to the `NotificationSent` event both are queued. I am using Redis connection. 

Also, the `handle` method above is on Listener class, right? 🤔 Not on the Notification class itself.

**Comment by awebartisan** [comment]
Tested it without Queueing Notification and Listener and was able to get response just fine.

> The response is a stream, which only exists during that request. It can't be serialised, and therefore queuing causes it to disappear. Patch is required in **laravel/nexmo-notification-channel** which will always turn that into a string instead of leaving it as a resource. - Chris Tankersley

Thank you for looking into this.

**Comment by SecondeJK** [comment]
This issue looks to have been resolved some time ago by @dragonmantank
